language: go

go:
  - "1.x"
  - "1.12"
  - tip

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

before_install:
  - env GO111MODULE=on go get github.com/mattn/goveralls

install:
  - env GO111MODULE=on go get -t -v ./...

script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test $(go list ./... | grep -v /example/) -coverprofile=gover.coverprofile
  - $GOPATH/bin/goveralls -coverprofile gover.coverprofile -service=travis-ci
